apiVersion: v1
kind: Service
metadata:
  name: studentdata-db-service
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      